# Generated by Django 4.2.9 on 2024-02-05 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=200)),
                ('max_passengers', models.IntegerField(null=True)),
                ('plate_number', models.CharField(max_length=200)),
                ('special_info', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('end_loc', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField(null=True, verbose_name='arrival time')),
                ('num_passengers', models.BigIntegerField(null=True)),
                ('shareable', models.BooleanField(default=True)),
                ('special_info', models.TextField(blank=True)),
                ('driver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.driver')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_party', models.BigIntegerField(null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
