# Generated by Django 4.2.9 on 2024-02-03 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0003_alter_driver_user_alter_rider_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='max_passengers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='num_passengers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='shareable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rideuser',
            name='num_party',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='max_passengers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.rider'),
        ),
    ]
