# Generated by Django 4.2.9 on 2024-02-03 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0004_ride_max_passengers_ride_num_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='max_passengers',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='start_loc',
        ),
        migrations.AddField(
            model_name='ride',
            name='arrival_time',
            field=models.DateTimeField(null=True, verbose_name='arrival time'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.driver'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='request_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
    ]
