# Generated by Django 4.2.9 on 2024-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_remove_ride_create_time_remove_ride_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='special_info',
            field=models.TextField(blank=True),
        ),
    ]
