# Generated by Django 4.2.9 on 2024-02-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_ride_special_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideuser',
            old_name='ride_id',
            new_name='ride',
        ),
        migrations.RenameField(
            model_name='rideuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='ride_id',
        ),
    ]
